[CUB-4303] Update get resources template schema
labforward/laboperator-workflow-schema pull request #35
Opened 2022-05-25 09:15 UTC by anneKay

### [CUB-4303]

### Description

Updated the template schema for get_resources action

### Manual PR Checklist

- [x] CHANGELOG entry added
- [x] ~Test coverage added~
- [x] Licenses checked
- [x] All related Jira tickets added to PR title
- [x] Description in Jira ticket is clear and up-to-date

[CUB-4303]: https://labforward.atlassian.net/browse/CUB-4303

2022-05-25 09:26 UTC, kgrhartlage commented on dist/workflow_step_template_schema.json
> +            "default": "1.0.1"
My bad, I did not regenerate the schema in the related PR. Let's update the PR template

```md
- [ ] CHANGELOG entry is correct
- [ ] I ran the build command after making changes to the schema
- [ ] I manually tested the changes and checked that related features do not have any regressions
```

2022-05-30 09:54 UTC, ignatiusreza requested changes

2022-05-30 09:54 UTC, ignatiusreza commented on .github/pull_request_template.md
> +- [ ] I ran the build command after making changes to the schema
this can be automated in CI.. I would remove this from the template, and create a ticket in JIRA to automate the check.. wdyt @kgrhartlage ?

2022-05-30 09:54 UTC, ignatiusreza commented on CHANGELOG.md
> +- [[CUB-4303]](https://labforward.atlassian.net/browse/CUB-4303) [Workflows] Update get resources template schema
:nail_care: 
```suggestion
- [[CUB-4303]](https://labforward.atlassian.net/browse/CUB-4303) [Workflows] Update get resources template schema

```

2022-05-30 10:15 UTC, anneKay commented on CHANGELOG.md
> +- [[CUB-4303]](https://labforward.atlassian.net/browse/CUB-4303) [Workflows] Update get resources template schema
I don't see the difference 🤔

2022-05-30 11:22 UTC, ignatiusreza commented on .github/pull_request_template.md
> +- [ ] I ran the build command after making changes to the schema
Correct.. we have something similar for the [middleware](https://github.com/labforward/laboperator-middleware/pull/23/commits/940cf52658fb94cdb40d3fe85a9e9a060f5403e3#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R53-R62)..

2022-05-30 16:40 UTC, ignatiusreza approved these changes
LGTM :+1:

#### Review checklist according to [SOP-13][1] & [SOP-014][2]

- [x] Code is readable
- [x] Test coverage is appropriate
- [x] CHANGELOG entry is correct
- [x] I manually tested the changes and checked that related capabilities do not have any regressions
- [x] I confirmed that all specifications linked to the issue are fulfilled
- [x] I checked newly added dependencies for their licenses

[1]: https://drive.google.com/file/d/1fD1ZcsBTywlMVTObTmNLrg55khrYMI_L/view
[2]: https://drive.google.com/file/d/1uRnMtykgw1Gzo2nRp-TPnESgmYoEIfBf/view

2022-05-30 16:45 UTC, merged